### ISSUE TITLE
Spconv Error

### ISSUE THREAD

**Issue by 99DHL** [Pointcept/PointTransformerV3#4]
Hi, I followed your instructions to train PointTransformerV3 for ScanNetV2 dataset but faced the following error. It seems like the error occurred due to the spconv operation with kernel size 5 in the Embedding layer linked below. My machine has 4 RTX 3090 GPUs and I used spconv-cu116 with Pytorch version 1.12.1+cu116.
[https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py#L485](https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py#L485)

Could you please tell me how I can fix this? Thank you again for your great work.

```
[2024-01-01 22:08:47,584 INFO train.py line 144 1382163] => Building hooks ...
[2024-01-01 22:08:47,584 INFO misc.py line 213 1382163] => Loading checkpoint & weight ...
[2024-01-01 22:08:47,584 INFO misc.py line 250 1382163] No weight found at: None
[2024-01-01 22:08:47,584 INFO train.py line 151 1382163] >>>>>>>>>>>>>>>> Start Training >>>>>>>>>>>>>>>>
[Exception|indice_conv|subm]feat=torch.Size([215907, 6]),w=torch.Size([32, 5, 5, 5, 6]),pair=torch.Size([2, 125, 215907]),pairnum=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0], device='cuda:2', dtype=torch.int32),act=215907,algo=ConvAlgo.Native
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
[Exception|indice_conv|subm]feat=torch.Size([268037, 6]),w=torch.Size([32, 5, 5, 5, 6]),pair=torch.Size([2, 125, 268037]),pairnum=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0], device='cuda:1', dtype=torch.int32),act=268037,algo=ConvAlgo.Native
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
[Exception|indice_conv|subm]feat=torch.Size([223221, 6]),w=torch.Size([32, 5, 5, 5, 6]),pair=torch.Size([2, 125, 223221]),pairnum=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0], device='cuda:0', dtype=torch.int32),act=223221,algo=ConvAlgo.Native
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
[Exception|indice_conv|subm]feat=torch.Size([280198, 6]),w=torch.Size([32, 5, 5, 5, 6]),pair=torch.Size([2, 125, 280198]),pairnum=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0], device='cuda:3', dtype=torch.int32),act=280198,algo=ConvAlgo.Native
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "tools/train.py", line 38, in <module>
    main()
  File "tools/train.py", line 27, in main
    launch(
  File "/home2/dhlee/Pointcept/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home2/dhlee/Pointcept/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/home2/dhlee/Pointcept/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/home2/dhlee/Pointcept/pointcept/engines/train.py", line 168, in train
    self.run_step()
  File "/home2/dhlee/Pointcept/pointcept/engines/train.py", line 182, in run_step
    output_dict = self.model(input_dict)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/dhlee/Pointcept/pointcept/models/default.py", line 54, in forward
    point = self.backbone(point)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/dhlee/Pointcept/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py", line 704, in forward
    point = self.embedding(point)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/dhlee/Pointcept/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py", line 514, in forward
    point = self.stem(point)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/dhlee/Pointcept/pointcept/models/modules.py", line 66, in forward
    input.sparse_conv_feat = module(input.sparse_conv_feat)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 327, in _conv_forward
    out_features = Fsp.indice_subm_conv(
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 116, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 327, in forward
    raise e
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 308, in forward
    return ops.indice_conv(features,
  File "/home2/dhlee/anaconda3/envs/ptv3/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 860, in indice_conv
    ConvGemmOps.indice_conv(alloc, ext_mm, GEMM_CPP, ALL_WEIGHT_IS_KRSC,
RuntimeError: dev2host /tmp/pip-build-env-gflaho1a/overlay/lib/python3.8/site-packages/cumm/include/tensorview/cuda/driverops.h:105
cuda failed with error 222 the provided PTX was compiled with an unsupported toolchain.. use CUDA_LAUNCH_BLOCKING=1 to get correct traceback.

```

**Comment by 99DHL** [comment]
I solved this issue by upgrading NVIDIA Driver version from 470 to 515.
