### ISSUE TITLE
NuScenes dataset：assert depth * 3 + len(self.offset).bit_length() <= 63

### ISSUE THREAD

**Issue by xiaosa269** [Pointcept/PointTransformerV3#84]
Thank you very much for your work. However, I encountered the following error while using Point Transformer v3 to train the NuScenes dataset：

[2024-08-12 20:17:09,807 INFO misc.py line 118 32371] Train: [1/64][246/7032] Data 0.002 (0.002) Batch 1.399 (1.510) Remain 188:39:41 loss: 1.7196 Lr: 0.00020
[2024-08-12 20:17:11,346 INFO misc.py line 118 32371] Train: [1/64][247/7032] Data 0.002 (0.002) Batch 1.540 (1.510) Remain 188:40:35 loss: 1.1980 Lr: 0.00020
[2024-08-12 20:17:12,857 INFO misc.py line 118 32371] Train: [1/64][248/7032] Data 0.002 (0.002) Batch 1.511 (1.510) Remain 188:40:36 loss: 1.5723 Lr: 0.00020
Traceback (most recent call last):
  File "exp/nuscenes/nuscenes_batch4_epoch64/code/tools/train.py", line 38, in <module>
    main()
  File "exp/nuscenes/nuscenes_batch4_epoch64/code/tools/train.py", line 27, in main
    launch(
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/tools/train.py", line 20, in main_worker
    trainer.train()
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/pointcept/engines/train.py", line 168, in train
    self.run_step()
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/pointcept/engines/train.py", line 182, in run_step
    output_dict = self.model(input_dict)
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/pointcept/models/default.py", line 55, in forward
    point = self.backbone(point)
  File "/home/xhy/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py", line 984, in forward
    point.serialization(order=self.order, shuffle_orders=self.shuffle_orders)
  File "/data/xhy_code/Pointcept/exp/nuscenes/nuscenes_batch4_epoch64/code/pointcept/models/utils/structure.py", line 69, in serialization
    assert depth * 3 + len(self.offset).bit_length() <= 63
AssertionError

My config file is as follows:
_base_ = ["../_base_/default_runtime.py"]

   # misc custom setting
batch_size = 4  # bs: total bs in all gpus
mix_prob = 0.8
empty_cache = False
enable_amp = True
find_unused_parameters=True
    # model settings
model = dict(
    type="DefaultSegmentorV2",
    num_classes=16,
    backbone_out_channels=64,
    backbone=dict(
        type="PT-v3m1",
        in_channels=4,
        order=["z", "z-trans", "hilbert", "hilbert-trans"],
        stride=(2, 2, 2, 2),
        enc_depths=(2, 2, 2, 6, 2),
        enc_channels=(32, 64, 128, 256, 512),
        enc_num_head=(2, 4, 8, 16, 32),
        enc_patch_size=(1024, 1024, 1024, 1024, 1024),
        dec_depths=(2, 2, 2, 2),
        dec_channels=(64, 64, 128, 256),
        dec_num_head=(4, 4, 8, 16),
        dec_patch_size=(1024, 1024, 1024, 1024),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        shuffle_orders=True,
        pre_norm=True,
        enable_rpe=False,
        enable_flash=True,
        upcast_attention=False,
        upcast_softmax=False,
        cls_mode=False,
        pdnorm_bn=False,
        pdnorm_ln=False,
        pdnorm_decouple=True,
        pdnorm_adaptive=False,
        pdnorm_affine=True,
        pdnorm_conditions=("nuScenes", "SemanticKITTI", "Waymo"),
    ),
    criteria=[
        dict(type="CrossEntropyLoss", loss_weight=1.0, ignore_index=-1),
        dict(type="LovaszLoss", mode="multiclass", loss_weight=1.0, ignore_index=-1),
    ],
)

# scheduler settings
epoch = 64
eval_epoch = 64
optimizer = dict(type="AdamW", lr=0.002, weight_decay=0.005)
scheduler = dict(
    type="OneCycleLR",
    max_lr=[0.002, 0.0002],
    pct_start=0.04,
    anneal_strategy="cos",
    div_factor=10.0,
    final_div_factor=100.0,
)
param_dicts = [dict(keyword="block", lr=0.0002)]

# dataset settings
dataset_type = "NuScenesDataset"
data_root = "/data/Nuscenes"
ignore_index = -1
names = [
    "barrier",
    "bicycle",
    "bus",
    "car",
    "construction_vehicle",
    "motorcycle",
    "pedestrian",
    "traffic_cone",
    "trailer",
    "truck",
    "driveable_surface",
    "other_flat",
    "sidewalk",
    "terrain",
    "manmade",
    "vegetation",
]

data = dict(
    num_classes=16,
    ignore_index=ignore_index,
    names=names,
    train=dict(
        type=dataset_type,
        split="train",
        data_root=data_root,
        transform=[
            # dict(type="RandomDropout", dropout_ratio=0.2, dropout_application_ratio=0.2),
            # dict(type="RandomRotateTargetAngle", angle=(1/2, 1, 3/2), center=[0, 0, 0], axis="z", p=0.75),
            dict(type="RandomRotate", angle=[-1, 1], axis="z", center=[0, 0, 0], p=0.5),
            # dict(type="RandomRotate", angle=[-1/6, 1/6], axis="x", p=0.5),
            # dict(type="RandomRotate", angle=[-1/6, 1/6], axis="y", p=0.5),
            dict(type="RandomScale", scale=[0.9, 1.1]),
            # dict(type="RandomShift", shift=[0.2, 0.2, 0.2]),
            dict(type="RandomFlip", p=0.5),
            dict(type="RandomJitter", sigma=0.005, clip=0.02),
            # dict(type="ElasticDistortion", distortion_params=[[0.2, 0.4], [0.8, 1.6]]),
            dict(
                type="GridSample",
                grid_size=0.05,
                hash_type="fnv",
                mode="train",
                keys=("coord", "strength", "segment"),
                return_grid_coord=True,
            ),
            # dict(type="SphereCrop", point_max=1000000, mode="random"),
            # dict(type="CenterShift", apply_z=False),
            dict(type="ToTensor"),
            dict(
                type="Collect",
                keys=("coord", "grid_coord", "segment"),
                feat_keys=("coord", "strength"),
            ),
        ],
        test_mode=False,
        ignore_index=ignore_index,
    ),
    val=dict(
        type=dataset_type,
        split="val",
        data_root=data_root,
        transform=[
            # dict(type="PointClip", point_cloud_range=(-51.2, -51.2, -4, 51.2, 51.2, 2.4)),
            dict(
                type="GridSample",
                grid_size=0.05,
                hash_type="fnv",
                mode="train",
                keys=("coord", "strength", "segment"),
                return_grid_coord=True,
            ),
            # dict(type="SphereCrop", point_max=1000000, mode='center'),
            dict(type="ToTensor"),
            dict(
                type="Collect",
                keys=("coord", "grid_coord", "segment"),
                feat_keys=("coord", "strength"),
            ),
        ],
        test_mode=False,
        ignore_index=ignore_index,
    ),
    test=dict(
        type=dataset_type,
        split="val",
        data_root=data_root,
        transform=[
            dict(type="Copy", keys_dict={"segment": "origin_segment"}),
            dict(
                type="GridSample",
                grid_size=0.025,
                hash_type="fnv",
                mode="train",
                keys=("coord", "strength", "segment"),
                return_inverse=True,
            ),
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type="GridSample",
                grid_size=0.05,
                hash_type="fnv",
                mode="test",
                return_grid_coord=True,
                keys=("coord", "strength"),
            ),
            crop=None,
            post_transform=[
                dict(type="ToTensor"),
                dict(
                    type="Collect",
                    keys=("coord", "grid_coord", "index"),
                    feat_keys=("coord", "strength"),
                ),
            ],
            aug_transform=[
                [dict(type="RandomScale", scale=[0.9, 0.9])],
                [dict(type="RandomScale", scale=[0.95, 0.95])],
                [dict(type="RandomScale", scale=[1, 1])],
                [dict(type="RandomScale", scale=[1.05, 1.05])],
                [dict(type="RandomScale", scale=[1.1, 1.1])],
                [
                    dict(type="RandomScale", scale=[0.9, 0.9]),
                    dict(type="RandomFlip", p=1),
                ],
                [
                    dict(type="RandomScale", scale=[0.95, 0.95]),
                    dict(type="RandomFlip", p=1),
                ],
                [dict(type="RandomScale", scale=[1, 1]), dict(type="RandomFlip", p=1)],
                [
                    dict(type="RandomScale", scale=[1.05, 1.05]),
                    dict(type="RandomFlip", p=1),
                ],
                [
                    dict(type="RandomScale", scale=[1.1, 1.1]),
                    dict(type="RandomFlip", p=1),
                ],
            ],
        ),
        ignore_index=ignore_index,
    ),
)

In the config file, I only modified batch_size = 4
I'm using two 12GB 3060 GPUs.How should I modify it to allow the network to train properly?
Thank you very much for your help.

**Comment by xiaosa269** [comment]
I have noticed that in the few epochs leading up to each error, there is a warning message as shown in the image
![image](https://github.com/user-attachments/assets/2eafe901-b62e-4026-b7e0-e3482d13d5ed)

**Comment by xiaosa269** [comment]
The issue has been resolved. I suspect it was caused by insufficient server memory.
