### ISSUE TITLE
s3dis FileNotFoundError

### ISSUE THREAD

**Issue by tanmay4269** [Pointcept/PointTransformerV3#99]
```
$ sh scripts/train.sh -g 1 -d s3dis -c semseg-pt-v3m1-0-rpe -n semseg-pt-v3m1-0-rpe
Experiment name: semseg-pt-v3m1-0-rpe
Python interpreter dir: python
Dataset: s3dis
Config: semseg-pt-v3m1-0-rpe
GPU Num: 1
 =========> CREATE EXP DIR <=========
Experiment dir: /home/tvg/3d-seg/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe
Loading config in: configs/s3dis/semseg-pt-v3m1-0-rpe.py
Running code in: exp/s3dis/semseg-pt-v3m1-0-rpe/code
 =========> RUN TASK <=========
Traceback (most recent call last):
  File "/home/tvg/3d-seg/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe/code/tools/train.py", line 38, in <module>
    main()
  File "/home/tvg/3d-seg/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe/code/tools/train.py", line 25, in main
    cfg = default_config_parser(args.config_file, args.options)
  File "/home/tvg/3d-seg/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/engines/defaults.py", line 115, in default_config_parser
    cfg = Config.fromfile(os.path.join(file_path[:sep], file_path[sep + 1 :]))
  File "/home/tvg/3d-seg/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/config.py", line 335, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename, use_predefined_variables)
  File "/home/tvg/3d-seg/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/config.py", line 181, in _file2dict
    check_file_exist(filename)
  File "/home/tvg/3d-seg/Pointcept/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/tvg/3d-seg/Pointcept/configs/s3dis/semseg/pt-v3m1-0-rpe.py" does not exist
```

**Comment by tanmay4269** [comment]
yeah my bad, thanks!
